query GetPartCategories {
    getPartCategories{
        name
        parts {
            part_id
            name
            image_url
            components {
                component {
                    name
                }
                quantity
            }
            current_quantity
        }
    }
}