query GetPartCategories {
    getPartCategories {
        part_category_id
        name
        parts {
            part_id
            name
            image_url
            current_quantity
            componentAssignments {
                component {
                    part_id
                    part_category_id
                    name
                    image_url
                    current_quantity
                }
                requiredQuantity
            }
            parentAssignments {
                parent {
                    part_id
                    part_category_id
                    name
                    image_url
                    current_quantity
                }
                requiredQuantity
            }
        }
    }
}

mutation CraftPart ($craftInput: CraftInput!){
    craft(CraftInput: $craftInput)
}

mutation FarmPart ($farmInput: FarmInput!){
    farm(FarmInput: $farmInput)
}