query GetPartCategories {
    getPartCategories {
        partCategoryId
        name
        parts {
            part_id
            name
            imageUrl
            currentQuantity
            componentAssignments {
                component {
                    part_id
                    partCategoryId
                    name
                    imageUrl
                    currentQuantity
                }
                requiredQuantity
            }
            parentAssignments {
                parent {
                    part_id
                    partCategoryId
                    name
                    imageUrl
                    currentQuantity
                }
                requiredQuantity
            }
        }
    }
}

mutation CraftPart ($craftInput: CraftInput!){
    craft(CraftInput: $craftInput)
}

mutation FarmPart ($farmInput: FarmInput!){
    farm(FarmInput: $farmInput)
}