query GetPartCategories {
    getPartCategories {
        part_category_id
        name
        parts {
            part_id
            name
            image_url
            current_quantity
            components {
                component {
                    part_id
                    name
                    image_url
                    current_quantity
                }
                required_quantity
            }
        }
    }
}

mutation CraftPart ($partId: Float!){
    craft(partId: $partId)
}

mutation FarmPart ($partId: Float!){
    farm(partId: $partId)
}